# https://moonrepo.dev/docs/config/project
$schema: https://moonrepo.dev/schemas/tasks.json

inheritedBy:
  language: typescript
  layer: application
  tag: vite

fileGroups:
  vite:
    - public/**/*
    - src/**/*
    - vite.config.ts

tasks:
  build:
    command: bunx --bun vite build
    description: Build the application for production using Vite
    inputs:
      - "@group(vite)"

  dev:
    command: bunx --bun vite
    description: Start the Vite development server
    preset: server

  preview:
    command: bunx --bun vite preview
    description: Serve the production build of the application
    deps:
      - build
    preset: server
