# https://moonrepo.dev/docs/config/tasks
$schema: https://moonrepo.dev/schemas/tasks.json

inheritedBy:
  language: typescript
  layer: library

tasks:
  build:
    command: bun build.ts
    description: Build the library
    inputs:
      - src/**/*
    outputs:
      - dist/**/*
